### ISSUE TITLE
Cursor or Pagination Threads

### ISSUE THREAD

**Issue by Jmallone** [iamdeepak92/threads-api#1]
Hi buddy, thank you for API! I have same questions:

(1) How did you perform this reverse engineering? Was it through app or web requests?

(2) Is there any way to retrieve the next posts? It seems that the API only returns around 20-25 user threads. Is there a "cursor_next" or something similar?

**Comment by iamdeepak92** [comment]
Thanks for appreciation 🙏.
1. You can access any profile on browser publically without login. e.g. https://www.threads.net/@zuck . I did it on browser with the help of developer tools.
2. Threads return only few posts without login. So to get more posts without login not possible.

**Comment by Jmallone** [comment]
Ah cool, until that day via the website it was not available, he did not enter, there was a screen with the login.
